<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" >
    <xacro:property name="box_length" value="0.01" />
    <xacro:property name="box_width" value="0.1" />
    <xacro:property name="box_height" value="0.1" />
    <link name="camera_link">
        <visual>
            <geometry>
                <box size="${box_length} ${box_width} ${box_height}" />
            </geometry>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <material name="grey" />
        </visual>
        <collision>
            <geometry>
                <box size="${box_length} ${box_width} ${box_height}" />
            </geometry>
            <origin xyz="0 0 0" rpy="0 0 0" />
        </collision>
        <xacro:box_inertia m="0.5" x="${box_length}" y="${box_width}" z="${box_height}" o_xyz="0 0 0"
                                                                                           o_rpy="0 0 0" />     
    </link>
    <joint name="base_camera_joint" type="fixed">
        <parent link="base_link"/>
        <child link="camera_link" />
        <origin xyz="${base_length / 2.0 + box_length / 2.0} 0 ${base_height / 2.0}" rpy="0 0 0"/>
    </joint>

    <gazebo reference="camera_link">
        <sensor name="camera" type="camera">
            <camera>
                <horizontal_fov>1.3962634</horizontal_fov>
                <image>
                    <width>640</width>
                    <height>480</height>
                    <format>R8G8B8</format>
                </image>
                <clip>
                    <near>0.1</near>
                    <far>15</far>
                </clip>
                <noise>
                    <type>gaussian</type>
                    <mean>0.0</mean>
                    <stddev>0.007</stddev>
                </noise>
                <optical_frame_id>camera_link</optical_frame_id>
                <camera_info_topic>camera/camera_info</camera_info_topic>
            </camera>
            <always_on>1</always_on>
            <update_rate>20</update_rate>
            <visualize>true</visualize>
            <topic>camera/image_raw</topic>
        </sensor>
    </gazebo>
</robot>
