<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" >
    <xacro:property name="base_length" value="1.0" />
    <xacro:property name="base_width" value="0.4" />
    <xacro:property name="base_height" value="0.2" />
    <xacro:property name="wheel_radius" value="0.1" />
    <xacro:property name="wheel_length" value="0.05" />

    <!-- <xacro:macro name="example_macro" params="a b c">
      <link name="dummy_link">
        <visual>
          <geometry>
            <box size="${a} ${b} ${c}" />
          </geometry>
        </visual>
      </link>
    </xacro:macro>

    <xacro:example_macro a="2" b="3" c="4" /> -->

    <xacro:macro name="box_inertia" params="m x y z o_xyz o_rpy">
        <inertial>
            <mass value="${m}" />
            <origin xyz="${o_xyz}" rpy="${o_rpy}" />
            <inertia ixx="${(m/12)*(y*y + z*z)}" ixy="0" ixz="0"
                     iyy="${(m/12)*(x*x + z*z)}" iyz="0"
                     izz="${(m/12)*(y*y + x*x)}" />
        </inertial>
    </xacro:macro>
    <xacro:macro name="wheel_inertia" params="m x z o_xyz o_rpy">
        <inertial>
            <mass value="${m}" />
            <origin xyz="${o_xyz}" rpy="${o_rpy}" />
            <inertia ixx="${(m/12)*(3*x*x + z*z)}" ixy="0" ixz="0"
                     iyy="${(m/12)*(3*x*x + z*z)}" iyz="0"
                     izz="${(m/2)*(x*x)}" />
        </inertial>
    </xacro:macro>

    <xacro:macro name="caster_inertia" params="m x o_xyz o_rpy">
        <inertial>
            <mass value="${m}" />
            <origin xyz="${o_xyz}" rpy="${o_rpy}" />
            <inertia ixx="${(2 * m / 5)*(x*x)}" ixy="0" ixz="0"
                     iyy="${(2 * m / 5)*(x*x)}" iyz="0"
                     izz="${(2 * m / 5)*(x*x)}" />
        </inertial>
    </xacro:macro>


    <link name="base_footprint">
        <!-- empty -->
    </link>

    <link name="base_link">
        <visual>
            <geometry>
                <box size="${base_length} ${base_width} ${base_height}" />
            </geometry>
            <origin xyz="0 0 ${base_height / 2.0}" rpy="0 0 0" />
            <material name="green" />
        </visual>
        <collision>
            <geometry>
                <box size="${base_length} ${base_width} ${base_height}" />
            </geometry>
            <origin xyz="0 0 ${base_height / 2.0}" rpy="0 0 0" />
        </collision>
        <xacro:box_inertia m="5.0" x="${base_length}" y="${base_width}" z="${base_height}" o_xyz="0 0 ${base_height / 2.0}"
                                                                                           o_rpy="0 0 0" />
        
    </link>

    <xacro:macro name="wheel_link" params="prefix">
        <link name="${prefix}_wheel_link">
            <visual>
                <geometry>
                    <cylinder radius="${wheel_radius}" length="${wheel_length}" />
                </geometry>
                <origin xyz="0 0 0" rpy="${pi / 2.0} 0 0" />
                <material name="grey" />
            </visual>
            <collision>
                <geometry>
                    <sphere radius="${wheel_radius}" />
                </geometry>
                <origin xyz="0 0 0" rpy="0 0 0" />
            </collision>
            <xacro:wheel_inertia m="1.0" x="${wheel_radius}" z="${wheel_length}" o_xyz="0 0 0"
                                                                               o_rpy="${pi / 2.0} 0 0" />
        </link>
    </xacro:macro>

    <xacro:wheel_link prefix="right" />
    <xacro:wheel_link prefix="left" />

    <link name="caster_wheel_link">
        <visual>
            <geometry>
                <sphere radius="0.05" />
            </geometry>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <material name="grey" />
        </visual>
        <collision>
            <geometry>
                <sphere radius="0.05" />
            </geometry>
            <origin xyz="0 0 0" rpy="0 0 0" />
        </collision>
        <xacro:caster_inertia m="0.5" x="0.05" o_xyz="0 0 0"
                                               o_rpy="0 0 0" />
    </link>
    <joint name="base_joint" type="fixed">
        <parent link="base_footprint" />
        <child link="base_link" />
        <origin xyz="0 0 0.1" rpy="0 0 0" />
    </joint>
    <joint name="base_caster_wheel_joint" type="fixed">
        <parent link="base_link" />
        <child link="caster_wheel_link" />
        <origin xyz="${base_length * (3.0/8.0)} 0 -0.05" rpy="0 0 0" />
    </joint>
    <joint name="right_wheel_base_joint" type="continuous">
        <parent link="base_link" />
        <child link="right_wheel_link" />
        <origin xyz="${-base_length * (3.0/8.0)} ${(base_width / 2.0) + (wheel_length / 2.0)} 0" rpy="0 0 0" />
        <axis xyz="0 1 0" />
        <limit lower="-1.57" upper="1.57" velocity="100" effort="100" />
    </joint>
    <joint name="left_wheel_base_joint" type="continuous">
        <parent link="base_link" />
        <child link="left_wheel_link" />
        <origin xyz="${-base_length * (3.0/8.0)} ${(-base_width / 2.0) + (-wheel_length / 2.0)} 0" rpy="0 0 0" />
        <axis xyz="0 1 0" />
        <limit lower="-1.57" upper="1.57" velocity="100" effort="100" />
    </joint>


</robot>