controller_manager:
  ros__parameters:
    update_rate: 30  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    bot_controller :
      type: diff_drive_controller/DiffDriveController
      

bot_controller:
  ros__parameters:
    type: diff_drive_controller/DiffDriveController
    left_wheel_names: ['base_front_left_hub_motor_wheel_joint']
    right_wheel_names: ['base_front_right_hub_motor_wheel_joint']

    publish_rate: 50.0
    cmd_vel_timeout: 0.5

    pose_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.01]
    twist_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.01]

    wheel_separation: 0.38161
    wheel_radius: 0.108
    wheels_per_side: 1

    wheel_separation_multiplier: 1.0
    left_wheel_radius_multiplier: 1.0
    right_wheel_radius_multiplier: 1.0

    use_stamped_vel: false
    base_frame_id: base_footprint

    publish_limited_velocity: true
    publish_wheel_data: true
    enable_odom_tf: true